githubAccessToken: xxxxx
userList:
  -
    username: xxx
  -
    username: xxx
repoList:
  -
    name: xxx/xxxx
  -
    name: xxx/xxxx
sprintList:
  -
    title: Bonus sprint 41
    duration: 2020-08-18..2020-08-24
  -
    title: Short sprint 42
    duration: 2020-08-25..2020-08-31
  -
    title: sprint 43
    duration: 2020-09-01..2020-09-14
